host: "localhost"
port: 2000
timeout: 10.0
sync_mode: true
fixed_delta_seconds: 0.05
world:
  traffic_manager:
    port: 8010
    hybrid_physics_mode: True
    synchronous_mode: True
  weather:
    cloudiness: 20
    precipitation: 0
    sun_altitude_angle: 10
  map_layer: 5  # 世界层级，级别越高越复杂,最高5级最小1级
  sampling_resolution: 2.0