world:
  map: "Town06_Opt"

obs_type: ["measurements","ocp_obs"]   # "image", "measurements"，"ocp_obs"

actors:
  ego_car: 'vehicle.tesla.model3'
  num_vehicles: 0
  random_place: False # 是否随机放置自车

image:
  width: 200
  height: 88
  channels: 3
  fov: 100

measurements:
  include: ["speed", "steer", "compass", "gps", "imu"]  # 速度（x,y),转向（steer）,方向弧度，

action:
  type: "continuous"
  continuous:
    throttle_range: [-1.0, 1.0]
    steer_range: [-1.0, 1.0]

reward_weights:
  speed: 2.0
  low_speed_penalty: 10
  centering: 1.0
  collision: -100.0
  angle: 0.01
  obstacle: -100.0

termination:
  collision_threshold: 0.1
  max_episode_steps: 1024     # 训练时候每回合最大步数
  obstacle_threshold: 1.5