train:
  num_episodes: 100    # 训练回合数
  num_envs: 1                  # 并行环境数
  total_timesteps: 1_000_000
  log_interval: 100          # 每多少步记录一次日志
  save_freq: 10            # 每多少回合保存一次模型
  continue: Ture    # 是否继续训练，如果需要继续训练，则需要填写模型地址
  model_path: 'checkpoints/20260112/a2c-v1.0_Town06_Opt_120733_episode=2.pth'
